### ISSUE TITLE
treat errors and warnings as info doesn't work

### ISSUE THREAD

**Issue by OneCyrus** [Dealogic/webpack-vsts-extension#24]
we have "treat errors and warnings" both set to info but the webpack task is still failing as warning and the build is marked as "partially succeeded".

>2017-05-16T15:25:36.2049714Z building the webpack project
>2017-05-16T15:25:36.2049714Z executing the command: node "D:\Build\8\s\src\project\node_modules\webpack\bin\webpack.js" --json
>2017-05-16T15:25:57.0332402Z [at-loader] Checking finished with 4 errors
>2017-05-16T15:25:57.0332402Z ##[debug]task result: Failed
>2017-05-16T15:25:57.0332402Z ##[error]webpack failed
>2017-05-16T15:25:57.1425306Z ##[error]Error: Command failed: node "D:\Build\8\s\src\project\node_modules\webpack\bin\webpack.js" --json`

**Comment by jkanczler** [comment]
Unfortunately you're right. Though the unit tests are passed, but actually the tests are ignoring the fact that webpack returns with an error, if there's an error during the compilation.

**Comment by jkanczler** [comment]
After the investigation: Turned out it's a breaking change in webpack command line (cli) 2.x. If there's a compile error in the webpack cli 1.x, it returns 0, returns successfully. It's changed in webpack-cli 2.x. If there's a compile error, the cli returns an error too. I'm going to fix this in 2.0.3.

**Comment by OneCyrus** [comment]
perfect! thank you!

**Comment by jkanczler** [comment]
merged to master, waiting to be released in 2.0.3
