### ISSUE TITLE
Add custom arguments to webpack command

### ISSUE THREAD

**Issue by fantasia949** [Dealogic/webpack-vsts-extension#50]
Is there any way to pass custom args directly to webpack command?

I can bypass this issue by moving the args to inside the config file, but with this way, I have to define separated config file for each environment.

**Comment by jkanczler** [comment]
It's interesting, can you explain this scenario a little bit more to me? Why do you need separated config file for each environment? What would you like to control with the arguments?

I'm asking this because in the version 3.0 of this extension we decided to rely on the webpack node.js API instead of calling the webpack CLI, so it's not possible anymore to give custom arguments, you have to control everything with the config files. But if you can provide me a very valid use case, when you can't workaround this issue easily, then I'm happy to try to find a solution to have an option to call the webpack CLI instead of using webpack node.js API.

**Comment by jkanczler** [comment]
It should be supported from 4.x as the task is using webpack.js cli again.
